import React, { Suspense } from 'react';
import {
  Route,
  Redirect,
  BrowserRouter as Router,
  Switch,
  Link,
} from 'react-router-dom';
import './App.less';

const FooPage = React.lazy(() => import('./pages/Foo'));
const BarPage = React.lazy(() => import('./pages/Bar'));

const App: React.FC = () => {
  return (
    <>
      <p>
        <code>It works!</code>
      </p>
      <div>
        <Router>
          <ul>
            <li><Link to="/foo">Foo Page</Link></li>
            <li><Link to="/bar">Bar Page</Link></li>
          </ul>
          <Suspense fallback={null}>
            <Switch>
              <Route path="/foo" component={() => <FooPage />} />
              <Route path="/bar" component={() => <BarPage />} />
              <Redirect from="/" to="/foo" />
            </Switch>
          </Suspense>
        </Router>
      </div>
      <p>Generated by <code>dollie.js</code></p>
    </>
  );
};

export default App;
